services:
  core:
    image: gallardo7761/java25-maven
    container_name: core
    restart: unless-stopped
    ports:
      - "127.0.0.1:10000:10000"
      - "127.0.0.1:5005:5005"
    networks:
      - backend-dev-net
    volumes:
      - ./:/data
      - /home/jomaa/.m2:/root/.m2
      - /home/jomaa/.config/backend/private.pem:/etc/backend/private.pem:ro
      - /home/jomaa/.config/backend/public.pem:/etc/backend/public.pem:ro
    working_dir: /data
    command: ["sh", "./entrypoint-core.sh"]
    environment:
      - SERVER_PORT=${CORE_PORT}
      - SERVER_SERVLET_CONTEXT_PATH=${CORE_CONTEXT_PATH}
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME_CORE}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_PRIVATE_KEY_PATH=${JWT_PRIVATE_KEY_PATH}
      - JWT_PUBLIC_KEY_PATH=${JWT_PUBLIC_KEY_PATH}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - SPRING_PROFILES_ACTIVE=dev

  huertos:
    image: gallardo7761/java25-maven
    container_name: huertos
    restart: unless-stopped
    ports:
      - "127.0.0.1:10001:10001"
      - "127.0.0.1:5006:5006"
    networks:
      - backend-dev-net
    depends_on:
      - core
    volumes:
      - ./:/data
      - ./uploads:/files
      - ./mail:/mail
      - /home/jomaa/.m2:/root/.m2
      - /home/jomaa/.config/backend/private.pem:/etc/backend/private.pem:ro
      - /home/jomaa/.config/backend/public.pem:/etc/backend/public.pem:ro
    working_dir: /data
    command: ["sh", "./entrypoint-huertos.sh"]
    environment:
      - SERVER_PORT=${HUERTOS_PORT}
      - SERVER_SERVLET_CONTEXT_PATH=${HUERTOS_CONTEXT_PATH}
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME_HUERTOS}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_PRIVATE_KEY_PATH=${JWT_PRIVATE_KEY_PATH}
      - JWT_PUBLIC_KEY_PATH=${JWT_PUBLIC_KEY_PATH}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - CORE_URL=${CORE_URL}
      - HUERTOS_USER=${HUERTOS_USER}
      - HUERTOS_PASS=${HUERTOS_PASS}
      - FILES_DIR=${FILES_DIR}
      - MAIL_LIST_PATH=${MAIL_LIST_PATH}
      - SPRING_PROFILES_ACTIVE=dev

networks:
  backend-dev-net:
    external: true