server:
  port: 8080
  servlet:
    context-path: /v2/core

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/huertos
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: WARN

filesDir: "/files"

jwt:
  private-key-path: ${JWT_PRIVATE_KEY}
  public-key-path: ${JWT_PUBLIC_KEY}
