server:
  port: 8081
  servlet:
    context-path: /v2/huertos

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/huertos
    username: admin
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

core:
  url: http://localhost:8080/v2/core

huertos:
  user: SYSTEM
  password: ${HUERTOS_PASS}

mail:
  list:
    path: /home/jomaa/Documentos/emails.csv
  smtp:
    server: smtp.huertosbellavista.es
    port: 587