server:
  port: 8081
  servlet:
    context-path: /v2/huertos

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/huertos
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org.hibernate.SQL: WARN

core:
  url: http://core:8080/v2/core

huertos:
  user: SYSTEM
  password: ${HUERTOS_PASS}

mail:
  list:
    path: /data/emails.csv
  smtp:
    server: smtp.huertosbellavista.es
    port: 587